/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.khannedy.antrian.hazelcast.view;

import com.hazelcast.core.IAtomicLong;
import java.awt.CardLayout;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author khannedy
 */
public class FormAntrian extends javax.swing.JFrame {

    private final BlockingQueue<Long> antrian;
    private final IAtomicLong nomorAntrian;

    /**
     * Creates new form FormAntrian
     *
     * @param antrian
     * @param nomorAntrian
     */
    public FormAntrian(BlockingQueue<Long> antrian, IAtomicLong nomorAntrian) {
        initComponents();
        this.antrian = antrian;
        this.nomorAntrian = nomorAntrian;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAplikasi = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelTeller = new javax.swing.JPanel();
        labelNoAntrian = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanelNasabah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelAmbilNoAntrian = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Antrian");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new java.awt.CardLayout());

        jButton1.setText("Aplikasi Nasabah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aplikasi Teller");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAplikasiLayout = new javax.swing.GroupLayout(jPanelAplikasi);
        jPanelAplikasi.setLayout(jPanelAplikasiLayout);
        jPanelAplikasiLayout.setHorizontalGroup(
            jPanelAplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAplikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanelAplikasiLayout.setVerticalGroup(
            jPanelAplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAplikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelAplikasi, "aplikasi");

        labelNoAntrian.setBackground(new java.awt.Color(255, 255, 255));
        labelNoAntrian.setFont(new java.awt.Font("Lucida Grande", 0, 100)); // NOI18N
        labelNoAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNoAntrian.setOpaque(true);

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jButton3.setText("Antrian Selanjutnya");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTellerLayout = new javax.swing.GroupLayout(jPanelTeller);
        jPanelTeller.setLayout(jPanelTellerLayout);
        jPanelTellerLayout.setHorizontalGroup(
            jPanelTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTellerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNoAntrian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTellerLayout.setVerticalGroup(
            jPanelTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTellerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNoAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelTeller, "teller");

        jLabel1.setText("No Antrian Anda :");

        labelAmbilNoAntrian.setFont(new java.awt.Font("Lucida Grande", 1, 100)); // NOI18N
        labelAmbilNoAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAmbilNoAntrian.setOpaque(true);

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jButton4.setText("Ambil No Antrian");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNasabahLayout = new javax.swing.GroupLayout(jPanelNasabah);
        jPanelNasabah.setLayout(jPanelNasabahLayout);
        jPanelNasabahLayout.setHorizontalGroup(
            jPanelNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNasabahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAmbilNoAntrian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelNasabahLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelNasabahLayout.setVerticalGroup(
            jPanelNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNasabahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAmbilNoAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelNasabah, "nasabah");

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "nasabah");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "teller");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            Long nomor = antrian.poll(2, TimeUnit.SECONDS);
            labelNoAntrian.setText(nomor.toString());
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(this, "Belum Ada Antrian Lagi");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Long no = nomorAntrian.incrementAndGet();
        antrian.add(no);
        labelAmbilNoAntrian.setText(no.toString());

    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelAplikasi;
    private javax.swing.JPanel jPanelNasabah;
    private javax.swing.JPanel jPanelTeller;
    private javax.swing.JLabel labelAmbilNoAntrian;
    private javax.swing.JLabel labelNoAntrian;
    // End of variables declaration//GEN-END:variables
}
